# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create("nombre" => "Seba" , "email" => "sebastian.admin123@gmail.com",  "password" => 123456 , "password_confirmation" => 123456 , "permiso" => "administrador" , "rut" => "18402173-0" , "numero_contacto" => 000000000 , "apellido_materno" => "Cornejo" , "apellido_paterno" => "Cornejo", "updated_at" => "2015-02-06 14:02:10", "created_at" => "2015-02-06 14:10:10")

#Temporales
			#User.create("nombre" => "Cliente" , "email" => "cliente@cliente", "password" => "123456", "permiso" => "cliente")
			#User.create("nombre" => "Profesional" , "email" => "profesional@profesional",  "password" => "123456", "permiso" => "profesional")

Comuna.create("nombre" => "Alhué")
Comuna.create("nombre" => "Buin")
Comuna.create("nombre" => "Calera de Tango")
Comuna.create("nombre" => "Cerrillos")
Comuna.create("nombre" => "Cerro Navia")
Comuna.create("nombre" => "Colina")
Comuna.create("nombre" => "Conchalí")
Comuna.create("nombre" => "Curacaví")
Comuna.create("nombre" => "El Bosque")
Comuna.create("nombre" => "El Monte")
Comuna.create("nombre" => "Estación Central")
Comuna.create("nombre" => "Huechuraba")
Comuna.create("nombre" => "Independencia")
Comuna.create("nombre" => "Isla de Maipo")
Comuna.create("nombre" => "La Cisterna")
Comuna.create("nombre" => "La Florida")
Comuna.create("nombre" => "La Granja")
Comuna.create("nombre" => "La Reina")
Comuna.create("nombre" => "Lampa")
Comuna.create("nombre" => "Las Condes")
Comuna.create("nombre" => "Lo Barnechea")
Comuna.create("nombre" => "Lo Espejo")
Comuna.create("nombre" => "Lo Prado")
Comuna.create("nombre" => "Macul")
Comuna.create("nombre" => "Maipú")
Comuna.create("nombre" => "María Pinto")
Comuna.create("nombre" => "Melipilla")
Comuna.create("nombre" => "Ñuñoa")
Comuna.create("nombre" => "Padre Hurtado")
Comuna.create("nombre" => "Paine")
Comuna.create("nombre" => "Pedro Aguirre Cerda")
Comuna.create("nombre" => "Peñaflor")
Comuna.create("nombre" => "Peñalolén")
Comuna.create("nombre" => "Pirque")
Comuna.create("nombre" => "Providencia")
Comuna.create("nombre" => "Pudahuel")
Comuna.create("nombre" => "Puente Alto")
Comuna.create("nombre" => "Quinta Normal")
Comuna.create("nombre" => "Recoleta")
Comuna.create("nombre" => "Renca")
Comuna.create("nombre" => "San Bernardo")
Comuna.create("nombre" => "San Joaquín")
Comuna.create("nombre" => "San José de Maipo")
Comuna.create("nombre" => "San Miguel")
Comuna.create("nombre" => "San Pedro")
Comuna.create("nombre" => "San Ramón")
Comuna.create("nombre" => "Santiago")
Comuna.create("nombre" => "Talagante")
Comuna.create("nombre" => "Til Til")
Comuna.create("nombre" => "Vitacura")

	
	
	
